import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
interface Props {
  userAgent?: string;
}
const  NEXT_KEY = 39
const  PREV_KEY = 37
const  UP_KEY = 38
export default class Page extends React.Component<Props> {
  currentCardCount = 6
  _handleKeyDown = (event:any) => {
    switch( event.keyCode ) {
     
        case NEXT_KEY:
            console.log ("show next card")
            if (document.getElementById ("card_"+this.currentCardCount) != null){ 
            document.getElementById ("card_"+this.currentCardCount).style.transform = "translate(-500px)"
            this.currentCardCount --
            }
            break;
        case PREV_KEY:
            console.log ("show previous card")
            if (document.getElementById ("card_"+(this.currentCardCount + 1)) != null){ 
            this.currentCardCount ++
            document.getElementById ("card_"+this.currentCardCount).style.transform = "translate(0px)"
            }
            break;
        case UP_KEY:
            console.log ("flip the card")
            document.getElementById ("card_"+this.currentCardCount).classList.toggle("flipme");
              // document.getElementById ("card_"+this.currentCardCount).style.transform = "translate(0px)"
            break;
        default: 
            break;
    }
}
   componentDidMount (){
      console.log ("inside componentDidMount")
      document.addEventListener("keydown", this._handleKeyDown);
  }
   cardClick = (event: React.MouseEvent<HTMLDivElement>) => {
   event.preventDefault();
   event.currentTarget.style.transform = "translate(-500px)"
   console.log ("clicked")
  };
  render() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {/* <div className = "[ transition: transform 0.6s] [transform-style: preserve-3d] absolute left-[28%] w-[550px] h-[300px]">
	<div>
<div  className = "[-webkit-backface-visibility: hidden] absolute bg-[lightblue] w-[100%] h-[100%] text-center border-2 border-[#ccc] rounded">
  Front
</div>
<div className = "[-webkit-backface-visibility: hidden] [transform:rotateY(180deg)] absolute bg-[lightblue] w-[100%] h-[100%] text-center border-2 border-[#ccc] rounded">
  Back
</div>
</div>
</div> */}
<div className = "displayContainer">
<div id = "card_0" onClick={this.cardClick} className="cardContainer">
  <div className="frontCard">
  Hello world
  </div>
  <div className="backCard">
  World Hello
  </div>
   
</div>
<div id = "card_1" onClick={this.cardClick} className="cardContainer">
  Hello guys whats up with you
</div>
<div id = "card_2" onClick={this.cardClick} className="cardContainer">
  can we start studying now
</div>
<div id = "card_3" onClick={this.cardClick} className="cardContainer">
 lorem ipsum
</div>
<div id = "card_4" onClick={this.cardClick} className="cardContainer">
  kotlin vs typescript
</div>
<div id = "card_5" onClick={this.cardClick} className="cardContainer">
  android architecture
</div>
<div id = "card_6" onClick={this.cardClick} className="cardContainer">
 what is view model
</div>
</div>
{/* 
<div className = {styles.cardContainer}>
	<div>
<div  class = "front card">
  Front 1
</div>
<div class = "back card">
  Back 1
</div>
</div>
</div> */}

              </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
}
